repos:
  # - repo: https://github.com/timothycrosley/isort
  #   rev: 4.3.21
  #   hooks:
  #     - id: isort
  #       additional_dependencies: [toml]
  #       args:
  #         [
  #           --multi-line=3,
  #           --trailing-comma,
  #           --force-grid-wrap=0,
  #           --use-parentheses,
  #         ]
  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.1.1
    hooks:
      - id: seed-isort-config
        args: ["--application-directories=src/prodstats:tests:tests/utils"]
  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21
    hooks:
      - id: isort
        additional_dependencies: [toml]
  - repo: https://github.com/python/black
    rev: 19.10b0
    hooks:
      - id: black
  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.0a2
    hooks:
      - id: flake8
        # additional_dependencies: [flake8-bugbear]
        args: [--max-line-length=100, --extend-ignore=E203]
        exclude: \*/db/migrations
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.5.0
    hooks:
      - id: check-byte-order-marker
      - id: trailing-whitespace
      - id: end-of-file-fixer
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.770
    hooks:
      - id: mypy
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.3
    hooks:
      - id: autoflake
        args:
          [
            "--in-place",
            "--remove-all-unused-imports",
            "--remove-unused-variable",
            "--ignore-init-module-imports",
          ]
