version: "3.7"

x-defaults: &defaults
  image: prodstats
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  env_file:
    - .env.compose
  depends_on:
    - redis
  volumes:
    - ./src/prodstats:/app/prodstats

services:
  # ihs:
  #   image: driftwood/ihs:latest
  #   command: ihs run web -b 0.0.0.0:5001
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - /Users/friedrichb/repo/ihs-deo:/app
  #   environment:
  #     DATABASE_URI: $IHS_DATABASE_URI
  #     LOG_LEVEL: 20
  # fracfocus:
  #   image: driftwood/fracfocus:latest
  #   command: fracfocus run web -b 0.0.0.0:5002
  #   ports:
  #     - "5002:5002"
  #   environment:
  #     DATABASE_HOST: docker.for.mac.host.internal
  #     DATABASE_USERNAME: fracfocus
  #     DATABASE_PASSWORD: null
  #     LOG_LEVEL: 10
  #     LOG_FORMAT: layman

  # web:
  #   <<: *defaults
  #   container_name: web
  #   command: prodstats dev server
  #   ports:
  #     - 8000
  worker_1:
    <<: *defaults
    container_name: prodstats_worker_1
    user: celeryuser
    command: prodstats run worker
  worker_2:
    <<: *defaults
    container_name: prodstats_worker_2
    user: celeryuser
    command: prodstats run worker

  # worker_3:
  #   <<: *defaults
  #   container_name: prodstats_worker_3
  #   user: celeryuser
  #   command: prodstats run worker
  # worker_4:
  #   <<: *defaults
  #   container_name: prodstats_worker_4
  #   user: celeryuser
  #   command: prodstats run worker
  flower:
    <<: *defaults
    container_name: prodstats_flower
    user: celeryuser
    command: prodstats run flower
    ports:
      - 5555:5555
  cron:
    <<: *defaults
    container_name: prodstats_cron
    user: celeryuser
    command: prodstats run cron
  redis:
    container_name: prodstats_redis
    image: redis
    build:
      context: ./redis
      dockerfile: Dockerfile
    command: redis-server  --save "" --appendonly no --loglevel notice --bind 0.0.0.0
    ports:
      - 6379:6379
    # volumes:
    #   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
    # command:
    #   - /usr/local/etc/redis/redis.conf
