version: "3.7"

x-defaults: &defaults
  image: driftwood/prodstats
  build:
    context: .
    dockerfile: Dockerfile
  restart: unless-stopped
  env_file:
    - .env.compose
  volumes:
    - ./src/prodstats:/app/prodstats

services:
  # ihs:
  #   image: driftwood/ihs:latest
  #   command: ihs run web -b 0.0.0.0:5001
  #   ports:
  #     - "5001:5001"
  #   volumes:
  #     - /Users/friedrichb/repo/ihs-deo:/app
  #   environment:
  #     DATABASE_URI: $IHS_DATABASE_URI
  #     LOG_LEVEL: 20
  # fracfocus:
  #   image: driftwood/fracfocus:latest
  #   command: fracfocus run web -b 0.0.0.0:5002
  #   ports:
  #     - "5002:5002"
  #   environment:
  #     DATABASE_HOST: docker.for.mac.host.internal
  #     DATABASE_USERNAME: fracfocus
  #     DATABASE_PASSWORD: null
  #     LOG_LEVEL: 10
  #     LOG_FORMAT: layman
  web:
    <<: *defaults
    container_name: prodstats_web
    command: prodstats run dev --host 0.0.0.0
    ports:
      - 8000:8000
  worker_1:
    <<: *defaults
    container_name: prodstats_worker
    user: celeryuser
    command: prodstats run worker
    depends_on:
      - redis
  # worker_2:
  #   <<: *defaults
  #   container_name: prodstats_worker_h
  #   user: celeryuser
  #   command: prodstats run worker -Q prodstats-h
  #   depends_on:
  #     - redis
  # worker_3:
  #   <<: *defaults
  #   container_name: prodstats_worker_v
  #   user: celeryuser
  #   command: prodstats run worker -Q prodstats-v
  #   depends_on:
  #     - redis
  # flower:
  #   <<: *defaults
  #   container_name: prodstats_flower
  #   user: celeryuser
  #   command: prodstats run flower
  #   ports:
  #     - 5555:5555
  #   depends_on:
  # - redis
  cron:
    <<: *defaults
    container_name: prodstats_cron
    user: celeryuser
    command: prodstats run cron --pidfile=
    depends_on:
      - redis
  # db_migration:
  #   <<: *defaults
  #   container_name: prodstats_db_migrations
  #   restart: "no"
  #   command: prodstats db upgrade
  redis:
    container_name: prodstats_redis
    image: redis
    command: redis-server  --save "" --appendonly no --loglevel notice --bind 0.0.0.0 --port 6380
    ports:
      - 6380:6380
  # volumes:
  #   - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
  # command:
  #   - /usr/local/etc/redis/redis.conf
