from db.models.bases import Base, db

__all__ = ["ProdMonthly", "ProdStat"]


class ProdMonthly(Base):
    __tablename__ = "production_monthly"

    api10 = db.Column(db.String(10), index=True, primary_key=True)
    prod_date = db.Column(db.Date())
    oil = db.Column(db.Numeric(19, 2))
    gas = db.Column(db.Numeric(19, 2))
    water = db.Column(db.Numeric(19, 2))
    gas_normalized_to_10k_ft = db.Column(db.Numeric(19, 2))
    oil_normalized_to_10k_ft = db.Column(db.Numeric(19, 2))
    gas_normalized_to_7500_ft = db.Column(db.Numeric(19, 2))
    oil_normalized_to_7500_ft = db.Column(db.Numeric(19, 2))
    gas_normalized_to_5k_ft = db.Column(db.Numeric(19, 2))
    oil_normalized_to_5k_ft = db.Column(db.Numeric(19, 2))
    prod_day = db.Column(db.Numeric(19, 2))
    prod_month = db.Column(db.Integer())
    peak_norm_month = db.Column(db.Integer())


class ProdStat(Base):
    __tablename__ = "prodstats"

    api10 = db.Column(db.String(10), index=True, primary_key=True)
    firstprod = db.Column(db.Date())
    lastprod = db.Column(db.Date())
    days_on = db.Column(db.Integer())
    monthsproducing = db.Column(db.Integer())
    gor_first6mo = db.Column(db.Integer())
    gor_first6mo_nonzero = db.Column(db.Integer())  # gor_first6mononzero
    oil_percent_first6mo = db.Column(db.Integer())
    oil_percent_last3mo = db.Column(db.Integer())
    oil_pk30 = db.Column(db.Integer())
    oil_pk30_date = db.Column(db.Date())
    oil_p30_prodmonth = db.Column(db.Integer())
    oil_avgdaily_last3mo = db.Column(db.Integer())
    oil_pdp_30kpbbl_last3mo = db.Column(db.Integer())
    oil_pknorm_perk_1mo = db.Column(db.Integer())
    oil_pknorm_perk_3mo = db.Column(db.Integer())
    oil_pknorm_perk_6mo = db.Column(db.Integer())
    oil_total = db.Column(db.Integer())
    oil_perk_first1mo = db.Column(db.Integer())
    oil_perk_first3mo = db.Column(db.Integer())
    oil_perk_first6mo = db.Column(db.Integer())
    oil_perk_first9mo = db.Column(db.Integer())
    oil_perk_first12mo = db.Column(db.Integer())
    oil_perk_first18mo = db.Column(db.Integer())
    oil_perk_first24mo = db.Column(db.Integer())
    oil_sum_last1mo = db.Column(db.Integer())
    oil_sum_last3mo = db.Column(db.Integer())
    oil_sum_last3mo_nonzero = db.Column(db.Integer())  # oil_sumnonzero_last3mo
    oil_sum_first1mo = db.Column(db.Integer())
    oil_sum_first3mo = db.Column(db.Integer())
    oil_sum_first6mo = db.Column(db.Integer())
    oil_sum_first9mo = db.Column(db.Integer())
    oil_sum_first12mo = db.Column(db.Integer())
    oil_sum_first18mo = db.Column(db.Integer())
    oil_sum_first24mo = db.Column(db.Integer())
    oil_sum_pknorm_1mo = db.Column(db.Integer())
    oil_sum_pknorm_3mo = db.Column(db.Integer())
    oil_sum_pknorm_6mo = db.Column(db.Integer())
    gas_pk30 = db.Column(db.Integer())
    gas_avgdaily_last3mo = db.Column(db.Integer())
    gas_pknorm_perk_1mo = db.Column(db.Integer())
    gas_pknorm_perk_3mo = db.Column(db.Integer())
    gas_pknorm_perk_6mo = db.Column(db.Integer())
    gas_total = db.Column(db.Integer())
    gas_perk_first1mo = db.Column(db.Integer())
    gas_perk_first3mo = db.Column(db.Integer())
    gas_perk_first6mo = db.Column(db.Integer())
    gas_perk_first9mo = db.Column(db.Integer())
    gas_perk_first12mo = db.Column(db.Integer())
    gas_perk_first18mo = db.Column(db.Integer())
    gas_perk_first24mo = db.Column(db.Integer())
    gas_sum_last1mo = db.Column(db.Integer())
    gas_sum_last3mo = db.Column(db.Integer())
    gas_sum_last3mo_nonzero = db.Column(db.Integer())  # gas_sumnonzero_last3mo
    gas_sum_first1mo = db.Column(db.Integer())
    gas_sum_first3mo = db.Column(db.Integer())
    gas_sum_first6mo = db.Column(db.Integer())
    gas_sum_first9mo = db.Column(db.Integer())
    gas_sum_first12mo = db.Column(db.Integer())
    gas_sum_first18mo = db.Column(db.Integer())
    gas_sum_first24mo = db.Column(db.Integer())
    gas_sum_pknorm_1mo = db.Column(db.Integer())
    gas_sum_pknorm_3mo = db.Column(db.Integer())
    gas_sum_pknorm_6mo = db.Column(db.Integer())
    boe_avgdaily_last3mo = db.Column(db.Integer())
    boe_pdp_30kpbbl_last3mo = db.Column(db.Integer())
    water_sum_last1mo = db.Column(db.Integer())
    water_sum_last3mo = db.Column(db.Integer())
    water_sumnonzero_last3mo = db.Column(db.Integer())
    # productiondatecutoff = db.Column(db.Date())
