"""empty message

Revision ID: 080ec40e892b
Revises: 5d2f7635450c
Create Date: 2020-04-14 10:02:56.526950

"""
import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

import const

# revision identifiers, used by Alembic.
revision = "080ec40e892b"
down_revision = "5d2f7635450c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas",
        sa.Column(
            "entity_type",
            sqlalchemy_utils.types.choice.ChoiceType(const.EntityType),
            nullable=False,
            primary_key=True,
        ),
    )
    op.add_column(
        "areas", sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("areas", "type")
    op.drop_column("areas", "last_run")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas",
        sa.Column(
            "last_run",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "areas",
        sa.Column("type", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    )
    op.drop_column("areas", "last_run_at")
    op.drop_column("areas", "entity_type")
    # ### end Alembic commands ###
