"""empty message

Revision ID: 0dd4334dbd5d
Revises: bb5936d7f5d4
Create Date: 2020-03-10 22:01:18.683465

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0dd4334dbd5d"
down_revision = "bb5936d7f5d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_header", sa.Column("first_prod_date", sa.Date(), nullable=True)
    )
    op.add_column(
        "production_header", sa.Column("last_prod_date", sa.Date(), nullable=True)
    )
    op.drop_column("production_header", "prod_date_last")
    op.drop_column("production_header", "prod_date_first")
    op.drop_index("idx_shapes_bent_stick", table_name="shapes")
    op.drop_index("idx_shapes_bent_stick_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_bhl", table_name="shapes")
    op.drop_index("idx_shapes_bhl_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_heel", table_name="shapes")
    op.drop_index("idx_shapes_heel_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_kop", table_name="shapes")
    op.drop_index("idx_shapes_kop_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_lateral_only", table_name="shapes")
    op.drop_index("idx_shapes_lateral_only_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_mid", table_name="shapes")
    op.drop_index("idx_shapes_mid_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_shl", table_name="shapes")
    op.drop_index("idx_shapes_shl_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_stick", table_name="shapes")
    op.drop_index("idx_shapes_stick_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_toe", table_name="shapes")
    op.drop_index("idx_shapes_toe_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_wellbore", table_name="shapes")
    op.drop_index("idx_shapes_wellbore_webmercator", table_name="shapes")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_shapes_wellbore_webmercator",
        "shapes",
        ["wellbore_webmercator"],
        unique=False,
    )
    op.create_index("idx_shapes_wellbore", "shapes", ["wellbore"], unique=False)
    op.create_index(
        "idx_shapes_toe_webmercator", "shapes", ["toe_webmercator"], unique=False
    )
    op.create_index("idx_shapes_toe", "shapes", ["toe"], unique=False)
    op.create_index(
        "idx_shapes_stick_webmercator", "shapes", ["stick_webmercator"], unique=False
    )
    op.create_index("idx_shapes_stick", "shapes", ["stick"], unique=False)
    op.create_index(
        "idx_shapes_shl_webmercator", "shapes", ["shl_webmercator"], unique=False
    )
    op.create_index("idx_shapes_shl", "shapes", ["shl"], unique=False)
    op.create_index(
        "idx_shapes_mid_webmercator", "shapes", ["mid_webmercator"], unique=False
    )
    op.create_index("idx_shapes_mid", "shapes", ["mid"], unique=False)
    op.create_index(
        "idx_shapes_lateral_only_webmercator",
        "shapes",
        ["lateral_only_webmercator"],
        unique=False,
    )
    op.create_index("idx_shapes_lateral_only", "shapes", ["lateral_only"], unique=False)
    op.create_index(
        "idx_shapes_kop_webmercator", "shapes", ["kop_webmercator"], unique=False
    )
    op.create_index("idx_shapes_kop", "shapes", ["kop"], unique=False)
    op.create_index(
        "idx_shapes_heel_webmercator", "shapes", ["heel_webmercator"], unique=False
    )
    op.create_index("idx_shapes_heel", "shapes", ["heel"], unique=False)
    op.create_index(
        "idx_shapes_bhl_webmercator", "shapes", ["bhl_webmercator"], unique=False
    )
    op.create_index("idx_shapes_bhl", "shapes", ["bhl"], unique=False)
    op.create_index(
        "idx_shapes_bent_stick_webmercator",
        "shapes",
        ["bent_stick_webmercator"],
        unique=False,
    )
    op.create_index("idx_shapes_bent_stick", "shapes", ["bent_stick"], unique=False)
    op.add_column(
        "production_header",
        sa.Column("prod_date_first", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_header",
        sa.Column("prod_date_last", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.drop_column("production_header", "last_prod_date")
    op.drop_column("production_header", "first_prod_date")
    # ### end Alembic commands ###
