"""added index to all updated_at columns

Revision ID: ce1209a5612f
Revises: a01159ac5fb0
Create Date: 2020-05-19 15:41:45.435326+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "ce1209a5612f"
down_revision = "a01159ac5fb0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f("ix_areas_updated_at"), "areas", ["updated_at"], unique=False)
    op.create_index(
        op.f("ix_depths_updated_at"), "depths", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_frac_parameters_updated_at"),
        "frac_parameters",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ip_tests_updated_at"), "ip_tests", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_known_entities_updated_at"),
        "known_entities",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_prodstats_updated_at"), "prodstats", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_production_header_updated_at"),
        "production_header",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_production_monthly_updated_at"),
        "production_monthly",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_runtime_stats_updated_at"),
        "runtime_stats",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_survey_points_updated_at"),
        "survey_points",
        ["updated_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_surveys_updated_at"), "surveys", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_well_links_updated_at"), "well_links", ["updated_at"], unique=False
    )
    op.create_index(
        op.f("ix_well_locations_updated_at"),
        "well_locations",
        ["updated_at"],
        unique=False,
    )
    op.create_index(op.f("ix_wells_updated_at"), "wells", ["updated_at"], unique=False)
    op.create_index(
        op.f("ix_wellstats_updated_at"), "wellstats", ["updated_at"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wellstats_updated_at"), table_name="wellstats")
    op.drop_index(op.f("ix_wells_updated_at"), table_name="wells")
    op.drop_index(op.f("ix_well_locations_updated_at"), table_name="well_locations")
    op.drop_index(op.f("ix_well_links_updated_at"), table_name="well_links")
    op.drop_index(op.f("ix_surveys_updated_at"), table_name="surveys")
    op.drop_index(op.f("ix_survey_points_updated_at"), table_name="survey_points")
    op.drop_index(op.f("ix_runtime_stats_updated_at"), table_name="runtime_stats")
    op.drop_index(
        op.f("ix_production_monthly_updated_at"), table_name="production_monthly"
    )
    op.drop_index(
        op.f("ix_production_header_updated_at"), table_name="production_header"
    )
    op.drop_index(op.f("ix_prodstats_updated_at"), table_name="prodstats")
    op.drop_index(op.f("ix_known_entities_updated_at"), table_name="known_entities")
    op.drop_index(op.f("ix_ip_tests_updated_at"), table_name="ip_tests")
    op.drop_index(op.f("ix_frac_parameters_updated_at"), table_name="frac_parameters")
    op.drop_index(op.f("ix_depths_updated_at"), table_name="depths")
    op.drop_index(op.f("ix_areas_updated_at"), table_name="areas")
    # ### end Alembic commands ###
