"""empty message

Revision ID: 840a80c52c7f
Revises: cab84848600b
Create Date: 2020-05-01 19:11:04.890231+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "840a80c52c7f"
down_revision = "cab84848600b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_prodstats_aggregate_type"),
        "prodstats",
        ["aggregate_type"],
        unique=False,
    )
    op.create_index(op.f("ix_prodstats_name"), "prodstats", ["name"], unique=False)
    op.create_index(
        op.f("ix_prodstats_property_name"), "prodstats", ["property_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_prodstats_property_name"), table_name="prodstats")
    op.drop_index(op.f("ix_prodstats_name"), table_name="prodstats")
    op.drop_index(op.f("ix_prodstats_aggregate_type"), table_name="prodstats")
    # ### end Alembic commands ###
