"""create known entities

Revision ID: cab84848600b
Revises: 0445df8a3cbd
Create Date: 2020-04-28 19:01:11.337078+00:00

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cab84848600b"
down_revision = "0445df8a3cbd"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "known_entities",
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("ihs_last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("enverus_last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("fracfocus_last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint(
            "entity_id", "entity_type", name=op.f("pk_known_entities")
        ),
    )
    op.create_index(
        "ix_known_entities_all",
        "known_entities",
        [
            "entity_type",
            "entity_id",
            "ihs_last_seen_at",
            "enverus_last_seen_at",
            "fracfocus_last_seen_at",
        ],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_known_entities_all", table_name="known_entities")
    op.drop_table("known_entities")
    # ### end Alembic commands ###
