"""add indices to depths.aggregate_type and ip_tests.test_date

Revision ID: a01159ac5fb0
Revises: 840a80c52c7f
Create Date: 2020-05-14 19:06:54.888535+00:00

"""
from alembic import op

# revision identifiers, used by Alembic.
revision = "a01159ac5fb0"
down_revision = "840a80c52c7f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_depths_aggregate_type"), "depths", ["aggregate_type"], unique=False
    )
    op.create_index(
        op.f("ix_ip_tests_test_date"), "ip_tests", ["test_date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ip_tests_test_date"), table_name="ip_tests")
    op.drop_index(op.f("ix_depths_aggregate_type"), table_name="depths")
    # ### end Alembic commands ###
