"""empty message

Revision ID: 2a7bc1f002c9
Revises: 75d7283cfc66
Create Date: 2020-04-14 09:49:18.421622

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a7bc1f002c9"
down_revision = "75d7283cfc66"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("areas", "count")
    op.drop_column("areas", "path")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas",
        sa.Column("path", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    )
    op.add_column(
        "areas", sa.Column("count", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
