"""empty message

Revision ID: 2bc48932d125
Revises: 9d248e7c87b4
Create Date: 2020-04-18 13:40:50.421013

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2bc48932d125"
down_revision = "9d248e7c87b4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "areas", "area", existing_type=sa.VARCHAR(length=25), nullable=False
    )
    op.add_column("frac_parameters", sa.Column("gen", sa.Integer(), nullable=True))
    op.add_column(
        "frac_parameters", sa.Column("gen_name", sa.String(length=10), nullable=True)
    )
    op.drop_column("frac_parameters", "gen_int")
    op.drop_column("frac_parameters", "gen_str")
    op.add_column(
        "production_header",
        sa.Column("boe_pdp_last3mo_per30kbbl", sa.Integer(), nullable=True),
    )
    op.add_column(
        "production_header",
        sa.Column("oil_pdp_last3mo_per30kbbl", sa.Integer(), nullable=True),
    )
    op.drop_column("production_header", "boe_pdp_last3mo_per30Kbbl")
    op.drop_column("production_header", "oil_pdp_last3mo_per30Kbbl")
    op.add_column(
        "production_monthly", sa.Column("boe_per10k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("boe_per1k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("boe_per3k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("boe_per5k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("boe_per7500", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("gas_per10k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("gas_per1k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("gas_per3k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("gas_per5k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("gas_per7500", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("oil_per10k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("oil_per1k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("oil_per3k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("oil_per5k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("oil_per7500", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("water_per10k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("water_per1k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("water_per3k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("water_per5k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("water_per7500", sa.Integer(), nullable=True)
    )
    op.drop_column("production_monthly", "oil_norm_5k")
    op.drop_column("production_monthly", "boe_norm_5k")
    op.drop_column("production_monthly", "gas_norm_7500")
    op.drop_column("production_monthly", "oil_norm_1k")
    op.drop_column("production_monthly", "oil_norm_10k")
    op.drop_column("production_monthly", "boe_norm_1k")
    op.drop_column("production_monthly", "gas_norm_10k")
    op.drop_column("production_monthly", "oil_norm_3k")
    op.drop_column("production_monthly", "boe_norm_7500")
    op.drop_column("production_monthly", "water_norm_1k")
    op.drop_column("production_monthly", "gas_norm_1k")
    op.drop_column("production_monthly", "gas_norm_5k")
    op.drop_column("production_monthly", "boe_norm_3k")
    op.drop_column("production_monthly", "water_norm_5k")
    op.drop_column("production_monthly", "oil_norm_7500")
    op.drop_column("production_monthly", "water_norm_10k")
    op.drop_column("production_monthly", "boe_norm_10k")
    op.drop_column("production_monthly", "gas_norm_3k")
    op.drop_column("production_monthly", "water_norm_3k")
    op.drop_column("production_monthly", "water_norm_7500")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_monthly",
        sa.Column("water_norm_7500", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("water_norm_3k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("gas_norm_3k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("boe_norm_10k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("water_norm_10k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("oil_norm_7500", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("water_norm_5k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("boe_norm_3k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("gas_norm_5k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("gas_norm_1k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("water_norm_1k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("boe_norm_7500", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("oil_norm_3k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("gas_norm_10k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("boe_norm_1k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("oil_norm_10k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("oil_norm_1k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("gas_norm_7500", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("boe_norm_5k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("oil_norm_5k", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("production_monthly", "water_per7500")
    op.drop_column("production_monthly", "water_per5k")
    op.drop_column("production_monthly", "water_per3k")
    op.drop_column("production_monthly", "water_per1k")
    op.drop_column("production_monthly", "water_per10k")
    op.drop_column("production_monthly", "oil_per7500")
    op.drop_column("production_monthly", "oil_per5k")
    op.drop_column("production_monthly", "oil_per3k")
    op.drop_column("production_monthly", "oil_per1k")
    op.drop_column("production_monthly", "oil_per10k")
    op.drop_column("production_monthly", "gas_per7500")
    op.drop_column("production_monthly", "gas_per5k")
    op.drop_column("production_monthly", "gas_per3k")
    op.drop_column("production_monthly", "gas_per1k")
    op.drop_column("production_monthly", "gas_per10k")
    op.drop_column("production_monthly", "boe_per7500")
    op.drop_column("production_monthly", "boe_per5k")
    op.drop_column("production_monthly", "boe_per3k")
    op.drop_column("production_monthly", "boe_per1k")
    op.drop_column("production_monthly", "boe_per10k")
    op.add_column(
        "production_header",
        sa.Column(
            "oil_pdp_last3mo_per30Kbbl",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_header",
        sa.Column(
            "boe_pdp_last3mo_per30Kbbl",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("production_header", "oil_pdp_last3mo_per30kbbl")
    op.drop_column("production_header", "boe_pdp_last3mo_per30kbbl")
    op.add_column(
        "frac_parameters",
        sa.Column("gen_str", sa.VARCHAR(length=10), autoincrement=False, nullable=True),
    )
    op.add_column(
        "frac_parameters",
        sa.Column("gen_int", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("frac_parameters", "gen_name")
    op.drop_column("frac_parameters", "gen")
    op.alter_column("areas", "area", existing_type=sa.VARCHAR(length=25), nullable=True)
    # ### end Alembic commands ###
