"""empty message

Revision ID: 2dd657b2f083
Revises: bd77e5350599
Create Date: 2020-03-07 14:49:12.353651

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2dd657b2f083"
down_revision = "bd77e5350599"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prodstat_definitions",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("uom", sa.String(length=50), nullable=True),
        sa.Column("agg_type", sa.String(length=50), nullable=True),
        sa.Column("stat_type", sa.String(length=50), nullable=True),
        sa.Column("stat_subtype", sa.String(length=50), nullable=True),
        sa.Column("start_month", sa.Integer(), nullable=True),
        sa.Column("end_month", sa.Integer(), nullable=True),
        sa.Column("norm_value", sa.Float(), nullable=True),
        sa.Column("norm_uom", sa.String(length=25), nullable=True),
        sa.Column("include_zero", sa.Boolean(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_prodstat_definitions_name"),
        "prodstat_definitions",
        ["name"],
        unique=True,
    )
    op.create_table(
        "prodstat_header",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api10", sa.String(length=10), nullable=False),
        sa.Column("api14s", sa.ARRAY(sa.Integer()), nullable=True),
        sa.Column("prod_date_first", sa.Date(), nullable=True),
        sa.Column("prod_date_last", sa.Date(), nullable=True),
        sa.Column("days_on", sa.Integer(), nullable=True),
        sa.Column("monthsproducing", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("api10"),
    )
    op.add_column("prodstats", sa.Column("comments", sa.String(), nullable=True))
    op.add_column("prodstats", sa.Column("prod_date_first", sa.Date(), nullable=True))
    op.add_column("prodstats", sa.Column("prod_date_last", sa.Date(), nullable=True))
    op.add_column(
        "prodstats", sa.Column("prod_month_first", sa.Integer(), nullable=True)
    )
    op.add_column(
        "prodstats", sa.Column("prod_month_last", sa.Integer(), nullable=True)
    )
    op.add_column(
        "prodstats", sa.Column("prodstat_def_id", sa.BigInteger(), nullable=False)
    )
    op.add_column("prodstats", sa.Column("value", sa.Float(), nullable=True))
    op.drop_index("ix_prodstats_api10", table_name="prodstats")
    op.create_foreign_key(
        None, "prodstats", "prodstat_definitions", ["prodstat_def_id"], ["id"]
    )
    op.drop_column("prodstats", "days_on")
    op.drop_column("prodstats", "gas_perk_first6mo")
    op.drop_column("prodstats", "oil_pknorm_perk_1mo")
    op.drop_column("prodstats", "oil_sum_first6mo")
    op.drop_column("prodstats", "oil_pdp_30kpbbl_last3mo")
    op.drop_column("prodstats", "gas_sum_first12mo")
    op.drop_column("prodstats", "boe_pdp_30kpbbl_last3mo")
    op.drop_column("prodstats", "oil_sum_first3mo")
    op.drop_column("prodstats", "oil_sum_first24mo")
    op.drop_column("prodstats", "gas_sum_last3mo_nonzero")
    op.drop_column("prodstats", "oil_sum_pknorm_1mo")
    op.drop_column("prodstats", "oil_sum_first12mo")
    op.drop_column("prodstats", "oil_perk_first3mo")
    op.drop_column("prodstats", "oil_sum_pknorm_3mo")
    op.drop_column("prodstats", "oil_sum_first9mo")
    op.drop_column("prodstats", "oil_sum_last3mo")
    op.drop_column("prodstats", "gas_perk_first1mo")
    op.drop_column("prodstats", "gas_pknorm_perk_1mo")
    op.drop_column("prodstats", "gor_first6mo_nonzero")
    op.drop_column("prodstats", "oil_sum_last3mo_nonzero")
    op.drop_column("prodstats", "oil_avgdaily_last3mo")
    op.drop_column("prodstats", "gas_total")
    op.drop_column("prodstats", "gas_pk30")
    op.drop_column("prodstats", "water_sum_last1mo")
    op.drop_column("prodstats", "boe_avgdaily_last3mo")
    op.drop_column("prodstats", "gas_sum_pknorm_1mo")
    op.drop_column("prodstats", "gas_perk_first18mo")
    op.drop_column("prodstats", "gas_sum_pknorm_6mo")
    op.drop_column("prodstats", "gas_sum_first6mo")
    op.drop_column("prodstats", "gas_sum_first18mo")
    op.drop_column("prodstats", "gas_sum_first1mo")
    op.drop_column("prodstats", "gas_sum_first24mo")
    op.drop_column("prodstats", "oil_perk_first12mo")
    op.drop_column("prodstats", "lastprod")
    op.drop_column("prodstats", "oil_pk30_date")
    op.drop_column("prodstats", "oil_sum_pknorm_6mo")
    op.drop_column("prodstats", "oil_perk_first6mo")
    op.drop_column("prodstats", "gor_first6mo")
    op.drop_column("prodstats", "oil_perk_first1mo")
    op.drop_column("prodstats", "oil_total")
    op.drop_column("prodstats", "oil_percent_last3mo")
    op.drop_column("prodstats", "oil_percent_first6mo")
    op.drop_column("prodstats", "oil_sum_last1mo")
    op.drop_column("prodstats", "gas_avgdaily_last3mo")
    op.drop_column("prodstats", "gas_perk_first3mo")
    op.drop_column("prodstats", "oil_pk30")
    op.drop_column("prodstats", "gas_sum_last3mo")
    op.drop_column("prodstats", "oil_pknorm_perk_3mo")
    op.drop_column("prodstats", "water_sum_last3mo")
    op.drop_column("prodstats", "gas_sum_first3mo")
    op.drop_column("prodstats", "firstprod")
    op.drop_column("prodstats", "oil_sum_first18mo")
    op.drop_column("prodstats", "oil_p30_prodmonth")
    op.drop_column("prodstats", "oil_perk_first9mo")
    op.drop_column("prodstats", "oil_pknorm_perk_6mo")
    op.drop_column("prodstats", "gas_perk_first12mo")
    op.drop_column("prodstats", "monthsproducing")
    op.drop_column("prodstats", "oil_perk_first24mo")
    op.drop_column("prodstats", "oil_perk_first18mo")
    op.drop_column("prodstats", "water_sumnonzero_last3mo")
    op.drop_column("prodstats", "gas_sum_first9mo")
    op.drop_column("prodstats", "gas_perk_first24mo")
    op.drop_column("prodstats", "gas_pknorm_perk_3mo")
    op.drop_column("prodstats", "gas_pknorm_perk_6mo")
    op.drop_column("prodstats", "gas_sum_pknorm_3mo")
    op.drop_column("prodstats", "gas_perk_first9mo")
    op.drop_column("prodstats", "oil_sum_first1mo")
    op.drop_column("prodstats", "gas_sum_last1mo")
    op.add_column(
        "production_monthly",
        sa.Column("gas_norm_10k_ft", sa.Numeric(precision=19, scale=2), nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("gas_norm_5k_ft", sa.Numeric(precision=19, scale=2), nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("gas_norm_7500_ft", sa.Numeric(precision=19, scale=2), nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("oil_norm_10k_ft", sa.Numeric(precision=19, scale=2), nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("oil_norm_5k_ft", sa.Numeric(precision=19, scale=2), nullable=True),
    )
    op.add_column(
        "production_monthly",
        sa.Column("oil_norm_7500_ft", sa.Numeric(precision=19, scale=2), nullable=True),
    )
    op.drop_index("ix_production_monthly_api10", table_name="production_monthly")
    op.drop_column("production_monthly", "gas_normalized_to_5k_ft")
    op.drop_column("production_monthly", "oil_normalized_to_10k_ft")
    op.drop_column("production_monthly", "gas_normalized_to_7500_ft")
    op.drop_column("production_monthly", "oil_normalized_to_5k_ft")
    op.drop_column("production_monthly", "gas_normalized_to_10k_ft")
    op.drop_column("production_monthly", "oil_normalized_to_7500_ft")
    op.drop_index("idx_shapes_bent_stick", table_name="shapes")
    op.drop_index("idx_shapes_bent_stick_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_bhl", table_name="shapes")
    op.drop_index("idx_shapes_bhl_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_heel", table_name="shapes")
    op.drop_index("idx_shapes_heel_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_kop", table_name="shapes")
    op.drop_index("idx_shapes_kop_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_lateral_only", table_name="shapes")
    op.drop_index("idx_shapes_lateral_only_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_mid", table_name="shapes")
    op.drop_index("idx_shapes_mid_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_shl", table_name="shapes")
    op.drop_index("idx_shapes_shl_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_stick", table_name="shapes")
    op.drop_index("idx_shapes_stick_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_toe", table_name="shapes")
    op.drop_index("idx_shapes_toe_webmercator", table_name="shapes")
    op.drop_index("idx_shapes_wellbore", table_name="shapes")
    op.drop_index("idx_shapes_wellbore_webmercator", table_name="shapes")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "idx_shapes_wellbore_webmercator",
        "shapes",
        ["wellbore_webmercator"],
        unique=False,
    )
    op.create_index("idx_shapes_wellbore", "shapes", ["wellbore"], unique=False)
    op.create_index(
        "idx_shapes_toe_webmercator", "shapes", ["toe_webmercator"], unique=False
    )
    op.create_index("idx_shapes_toe", "shapes", ["toe"], unique=False)
    op.create_index(
        "idx_shapes_stick_webmercator", "shapes", ["stick_webmercator"], unique=False
    )
    op.create_index("idx_shapes_stick", "shapes", ["stick"], unique=False)
    op.create_index(
        "idx_shapes_shl_webmercator", "shapes", ["shl_webmercator"], unique=False
    )
    op.create_index("idx_shapes_shl", "shapes", ["shl"], unique=False)
    op.create_index(
        "idx_shapes_mid_webmercator", "shapes", ["mid_webmercator"], unique=False
    )
    op.create_index("idx_shapes_mid", "shapes", ["mid"], unique=False)
    op.create_index(
        "idx_shapes_lateral_only_webmercator",
        "shapes",
        ["lateral_only_webmercator"],
        unique=False,
    )
    op.create_index("idx_shapes_lateral_only", "shapes", ["lateral_only"], unique=False)
    op.create_index(
        "idx_shapes_kop_webmercator", "shapes", ["kop_webmercator"], unique=False
    )
    op.create_index("idx_shapes_kop", "shapes", ["kop"], unique=False)
    op.create_index(
        "idx_shapes_heel_webmercator", "shapes", ["heel_webmercator"], unique=False
    )
    op.create_index("idx_shapes_heel", "shapes", ["heel"], unique=False)
    op.create_index(
        "idx_shapes_bhl_webmercator", "shapes", ["bhl_webmercator"], unique=False
    )
    op.create_index("idx_shapes_bhl", "shapes", ["bhl"], unique=False)
    op.create_index(
        "idx_shapes_bent_stick_webmercator",
        "shapes",
        ["bent_stick_webmercator"],
        unique=False,
    )
    op.create_index("idx_shapes_bent_stick", "shapes", ["bent_stick"], unique=False)
    op.add_column(
        "production_monthly",
        sa.Column(
            "oil_normalized_to_7500_ft",
            sa.NUMERIC(precision=19, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_monthly",
        sa.Column(
            "gas_normalized_to_10k_ft",
            sa.NUMERIC(precision=19, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_monthly",
        sa.Column(
            "oil_normalized_to_5k_ft",
            sa.NUMERIC(precision=19, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_monthly",
        sa.Column(
            "gas_normalized_to_7500_ft",
            sa.NUMERIC(precision=19, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_monthly",
        sa.Column(
            "oil_normalized_to_10k_ft",
            sa.NUMERIC(precision=19, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "production_monthly",
        sa.Column(
            "gas_normalized_to_5k_ft",
            sa.NUMERIC(precision=19, scale=2),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.create_index(
        "ix_production_monthly_api10", "production_monthly", ["api10"], unique=False
    )
    op.drop_column("production_monthly", "oil_norm_7500_ft")
    op.drop_column("production_monthly", "oil_norm_5k_ft")
    op.drop_column("production_monthly", "oil_norm_10k_ft")
    op.drop_column("production_monthly", "gas_norm_7500_ft")
    op.drop_column("production_monthly", "gas_norm_5k_ft")
    op.drop_column("production_monthly", "gas_norm_10k_ft")
    op.add_column(
        "prodstats",
        sa.Column("gas_sum_last1mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_sum_first1mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_perk_first9mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_sum_pknorm_3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_pknorm_perk_6mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_pknorm_perk_3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_perk_first24mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("gas_sum_first9mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "water_sumnonzero_last3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_perk_first18mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_perk_first24mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("monthsproducing", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_perk_first12mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_pknorm_perk_6mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_perk_first9mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_p30_prodmonth", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_sum_first18mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("firstprod", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column("gas_sum_first3mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "water_sum_last3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_pknorm_perk_3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("gas_sum_last3mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_pk30", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_perk_first3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_avgdaily_last3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_sum_last1mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_percent_first6mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_percent_last3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_total", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_perk_first1mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("gor_first6mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_perk_first6mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_sum_pknorm_6mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_pk30_date", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column("lastprod", sa.DATE(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_perk_first12mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_sum_first24mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("gas_sum_first1mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_sum_first18mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("gas_sum_first6mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_sum_pknorm_6mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_perk_first18mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_sum_pknorm_1mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "boe_avgdaily_last3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "water_sum_last1mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("gas_pk30", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column("gas_total", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_avgdaily_last3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_sum_last3mo_nonzero", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gor_first6mo_nonzero", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_pknorm_perk_1mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_perk_first1mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_sum_last3mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_sum_first9mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_sum_pknorm_3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_perk_first3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_sum_first12mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_sum_pknorm_1mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_sum_last3mo_nonzero", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_sum_first24mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_sum_first3mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "boe_pdp_30kpbbl_last3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_sum_first12mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_pdp_30kpbbl_last3mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("oil_sum_first6mo", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "oil_pknorm_perk_1mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column(
            "gas_perk_first6mo", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "prodstats",
        sa.Column("days_on", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "prodstats", type_="foreignkey")
    op.create_index("ix_prodstats_api10", "prodstats", ["api10"], unique=False)
    op.drop_column("prodstats", "value")
    op.drop_column("prodstats", "prodstat_def_id")
    op.drop_column("prodstats", "prod_month_last")
    op.drop_column("prodstats", "prod_month_first")
    op.drop_column("prodstats", "prod_date_last")
    op.drop_column("prodstats", "prod_date_first")
    op.drop_column("prodstats", "comments")
    op.drop_table("prodstat_header")
    op.drop_index(
        op.f("ix_prodstat_definitions_name"), table_name="prodstat_definitions"
    )
    op.drop_table("prodstat_definitions")
    # ### end Alembic commands ###
