"""empty message

Revision ID: 3b46bad69b6b
Revises: 822a7a725ef0
Create Date: 2020-03-05 17:49:04.311343

"""
from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils
import geoalchemy2


# revision identifiers, used by Alembic.
revision = "3b46bad69b6b"
down_revision = "822a7a725ef0"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("well", sa.Column("status", sa.String(length=50), nullable=True))
    op.create_index(op.f("ix_well_basin"), "well", ["basin"], unique=False)
    op.create_index(op.f("ix_well_county"), "well", ["county"], unique=False)
    op.create_index(
        "well_basin_holedir_isprod_idx",
        "well",
        ["basin", "hole_direction", "is_producing"],
        unique=False,
    )
    op.create_index("well_basin_status_idx", "well", ["basin", "status"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("well_basin_status_idx", table_name="well")
    op.drop_index("well_basin_holedir_isprod_idx", table_name="well")
    op.drop_index(op.f("ix_well_county"), table_name="well")
    op.drop_index(op.f("ix_well_basin"), table_name="well")
    op.drop_column("well", "status")
    # ### end Alembic commands ###
