"""empty message

Revision ID: 4b9cf99f1075
Revises: 124e44d9264c
Create Date: 2020-03-28 12:24:03.512309

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4b9cf99f1075"
down_revision = "124e44d9264c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("surveys", sa.Column("survey_base", sa.Integer(), nullable=True))
    op.add_column(
        "surveys", sa.Column("survey_base_uom", sa.String(length=10), nullable=True)
    )
    op.add_column("surveys", sa.Column("survey_top", sa.Integer(), nullable=True))
    op.add_column(
        "surveys", sa.Column("survey_top_uom", sa.String(length=10), nullable=True)
    )
    op.drop_column("surveys", "depth_base_uom")
    op.drop_column("surveys", "depth_top")
    op.drop_column("surveys", "depth_base")
    op.drop_column("surveys", "depth_top_uom")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "surveys",
        sa.Column(
            "depth_top_uom", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "surveys",
        sa.Column("depth_base", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "surveys",
        sa.Column("depth_top", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "surveys",
        sa.Column(
            "depth_base_uom", sa.VARCHAR(length=10), autoincrement=False, nullable=True
        ),
    )
    op.drop_column("surveys", "survey_top_uom")
    op.drop_column("surveys", "survey_top")
    op.drop_column("surveys", "survey_base_uom")
    op.drop_column("surveys", "survey_base")
    # ### end Alembic commands ###
