"""empty message

Revision ID: 5d2f7635450c
Revises: 2a7bc1f002c9
Create Date: 2020-04-14 09:50:38.905179

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "5d2f7635450c"
down_revision = "2a7bc1f002c9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas", sa.Column("last_run", sa.DateTime(timezone=True), nullable=True)
    )
    op.drop_column("areas", "last_sync")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas",
        sa.Column(
            "last_sync",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_column("areas", "last_run")
    # ### end Alembic commands ###
