"""empty message

Revision ID: 72c5ff99b815
Revises: d7da4e4d0cc1
Create Date: 2020-04-11 15:23:16.216694

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "72c5ff99b815"
down_revision = "d7da4e4d0cc1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "frac_parameters", sa.Column("lateral_length", sa.Integer(), nullable=True)
    )
    op.drop_column("frac_parameters", "lateral_lenth")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "frac_parameters",
        sa.Column("lateral_lenth", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.drop_column("frac_parameters", "lateral_length")
    # ### end Alembic commands ###
