"""empty message

Revision ID: 75d7283cfc66
Revises: b05ea6419144
Create Date: 2020-04-14 09:05:01.690166

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "75d7283cfc66"
down_revision = "b05ea6419144"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("areas", sa.Column("count", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("areas", "count")
    # ### end Alembic commands ###
