"""empty message

Revision ID: 7e8c7b984e31
Revises:
Create Date: 2020-03-02 18:33:16.030507

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7e8c7b984e31"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "prodstats",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api10", sa.String(length=10), nullable=False),
        sa.Column("perfll", sa.Integer(), nullable=True),
        sa.Column("frac_bbl", sa.Integer(), nullable=True),
        sa.Column("frac_lb", sa.Integer(), nullable=True),
        sa.Column("frac_bbl_ft", sa.Integer(), nullable=True),
        sa.Column("frac_lb_ft", sa.Integer(), nullable=True),
        sa.Column("frac_gen_int", sa.Integer(), nullable=True),
        sa.Column("frac_gen_str", sa.String(), nullable=True),
        sa.Column("firstprod", sa.Date(), nullable=True),
        sa.Column("lastprod", sa.Date(), nullable=True),
        sa.Column("days_on", sa.Integer(), nullable=True),
        sa.Column("monthsproducing", sa.Integer(), nullable=True),
        sa.Column("gor_first6mo", sa.Integer(), nullable=True),
        sa.Column("gor_first6mononzero", sa.Integer(), nullable=True),
        sa.Column("oil_percent_first6mo", sa.Integer(), nullable=True),
        sa.Column("oil_percent_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_pk30", sa.Integer(), nullable=True),
        sa.Column("oil_pk30_date", sa.Date(), nullable=True),
        sa.Column("oil_p30_prodmonth", sa.Integer(), nullable=True),
        sa.Column("oil_avgdaily_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_pdp_30kpbbl_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_pknorm_perk_1mo", sa.Integer(), nullable=True),
        sa.Column("oil_pknorm_perk_3mo", sa.Integer(), nullable=True),
        sa.Column("oil_pknorm_perk_6mo", sa.Integer(), nullable=True),
        sa.Column("oil_total", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first1mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first3mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first6mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first9mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first12mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first18mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first24mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_last1mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_sumnonzero_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first1mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first3mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first6mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first9mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first12mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first18mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first24mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_pknorm_1mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_pknorm_3mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_pknorm_6mo", sa.Integer(), nullable=True),
        sa.Column("gas_pk30", sa.Integer(), nullable=True),
        sa.Column("gas_avgdaily_last3mo", sa.Integer(), nullable=True),
        sa.Column("gas_pknorm_perk_1mo", sa.Integer(), nullable=True),
        sa.Column("gas_pknorm_perk_3mo", sa.Integer(), nullable=True),
        sa.Column("gas_pknorm_perk_6mo", sa.Integer(), nullable=True),
        sa.Column("gas_total", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first1mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first3mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first6mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first9mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first12mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first18mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first24mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_last1mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_last3mo", sa.Integer(), nullable=True),
        sa.Column("gas_sumnonzero_last3mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first1mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first3mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first6mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first9mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first12mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first18mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first24mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_pknorm_1mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_pknorm_3mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_pknorm_6mo", sa.Integer(), nullable=True),
        sa.Column("boe_avgdaily_last3mo", sa.Integer(), nullable=True),
        sa.Column("boe_pdp_30kpbbl_last3mo", sa.Integer(), nullable=True),
        sa.Column("water_sum_last1mo", sa.Integer(), nullable=True),
        sa.Column("water_sum_last3mo", sa.Integer(), nullable=True),
        sa.Column("water_sumnonzero_last3mo", sa.Integer(), nullable=True),
        sa.Column("productiondatecutoff", sa.Date(), nullable=True),
        sa.Column("perf_upper_min", sa.Integer(), nullable=True),
        sa.Column("perf_lower_max", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("api10"),
    )
    op.create_index(op.f("ix_prodstats_api10"), "prodstats", ["api10"], unique=False)
    op.create_table(
        "production_monthly",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api10", sa.String(length=10), nullable=False),
        sa.Column("prod_date", sa.Date(), nullable=True),
        sa.Column("oil", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column("gas", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column("water", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column(
            "gas_normalized_to_10k_ft", sa.Numeric(precision=19, scale=2), nullable=True
        ),
        sa.Column(
            "oil_normalized_to_10k_ft", sa.Numeric(precision=19, scale=2), nullable=True
        ),
        sa.Column(
            "gas_normalized_to_7500_ft",
            sa.Numeric(precision=19, scale=2),
            nullable=True,
        ),
        sa.Column(
            "oil_normalized_to_7500_ft",
            sa.Numeric(precision=19, scale=2),
            nullable=True,
        ),
        sa.Column(
            "gas_normalized_to_5k_ft", sa.Numeric(precision=19, scale=2), nullable=True
        ),
        sa.Column(
            "oil_normalized_to_5k_ft", sa.Numeric(precision=19, scale=2), nullable=True
        ),
        sa.Column("prod_day", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column("prod_month", sa.Integer(), nullable=True),
        sa.Column("peak_norm_month", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("api10"),
    )
    op.create_index(
        op.f("ix_production_monthly_api10"),
        "production_monthly",
        ["api10"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_production_monthly_api10"), table_name="production_monthly")
    op.drop_table("production_monthly")
    op.drop_index(op.f("ix_prodstats_api10"), table_name="prodstats")
    op.drop_table("prodstats")
    # ### end Alembic commands ###
