"""empty message

Revision ID: 822a7a725ef0
Revises: 244869cf6945
Create Date: 2020-03-05 17:13:59.860800

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "822a7a725ef0"
down_revision = "244869cf6945"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "depths",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api14", sa.String(length=14), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("value", sa.Integer(), nullable=True),
        sa.Column("grid_id", sa.Integer(), nullable=True),
        sa.Column("formation", sa.String(length=50), nullable=True),
        sa.Column("into_formation_feet", sa.Integer(), nullable=True),
        sa.Column("into_formation_percent", sa.Float(), nullable=True),
        sa.Column("above_next_formation_feet", sa.Integer(), nullable=True),
        sa.Column("above_next_formation_percent", sa.Float(), nullable=True),
        sa.Column("overlap_feet", sa.Integer(), nullable=True),
        sa.Column("overlap_percent", sa.Float(), nullable=True),
        sa.Column("in_target", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("api14", "name"),
    )
    op.create_index(op.f("ix_depths_api14"), "depths", ["api14"], unique=False)
    op.create_index(op.f("ix_depths_name"), "depths", ["name"], unique=False)
    op.create_table(
        "prodstats",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api10", sa.String(length=10), nullable=False),
        sa.Column("firstprod", sa.Date(), nullable=True),
        sa.Column("lastprod", sa.Date(), nullable=True),
        sa.Column("days_on", sa.Integer(), nullable=True),
        sa.Column("monthsproducing", sa.Integer(), nullable=True),
        sa.Column("gor_first6mo", sa.Integer(), nullable=True),
        sa.Column("gor_first6mo_nonzero", sa.Integer(), nullable=True),
        sa.Column("oil_percent_first6mo", sa.Integer(), nullable=True),
        sa.Column("oil_percent_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_pk30", sa.Integer(), nullable=True),
        sa.Column("oil_pk30_date", sa.Date(), nullable=True),
        sa.Column("oil_p30_prodmonth", sa.Integer(), nullable=True),
        sa.Column("oil_avgdaily_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_pdp_30kpbbl_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_pknorm_perk_1mo", sa.Integer(), nullable=True),
        sa.Column("oil_pknorm_perk_3mo", sa.Integer(), nullable=True),
        sa.Column("oil_pknorm_perk_6mo", sa.Integer(), nullable=True),
        sa.Column("oil_total", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first1mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first3mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first6mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first9mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first12mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first18mo", sa.Integer(), nullable=True),
        sa.Column("oil_perk_first24mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_last1mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_last3mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_last3mo_nonzero", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first1mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first3mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first6mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first9mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first12mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first18mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_first24mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_pknorm_1mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_pknorm_3mo", sa.Integer(), nullable=True),
        sa.Column("oil_sum_pknorm_6mo", sa.Integer(), nullable=True),
        sa.Column("gas_pk30", sa.Integer(), nullable=True),
        sa.Column("gas_avgdaily_last3mo", sa.Integer(), nullable=True),
        sa.Column("gas_pknorm_perk_1mo", sa.Integer(), nullable=True),
        sa.Column("gas_pknorm_perk_3mo", sa.Integer(), nullable=True),
        sa.Column("gas_pknorm_perk_6mo", sa.Integer(), nullable=True),
        sa.Column("gas_total", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first1mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first3mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first6mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first9mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first12mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first18mo", sa.Integer(), nullable=True),
        sa.Column("gas_perk_first24mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_last1mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_last3mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_last3mo_nonzero", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first1mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first3mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first6mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first9mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first12mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first18mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_first24mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_pknorm_1mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_pknorm_3mo", sa.Integer(), nullable=True),
        sa.Column("gas_sum_pknorm_6mo", sa.Integer(), nullable=True),
        sa.Column("boe_avgdaily_last3mo", sa.Integer(), nullable=True),
        sa.Column("boe_pdp_30kpbbl_last3mo", sa.Integer(), nullable=True),
        sa.Column("water_sum_last1mo", sa.Integer(), nullable=True),
        sa.Column("water_sum_last3mo", sa.Integer(), nullable=True),
        sa.Column("water_sumnonzero_last3mo", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("api10"),
    )
    op.create_index(op.f("ix_prodstats_api10"), "prodstats", ["api10"], unique=False)
    op.create_table(
        "production_monthly",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api10", sa.String(length=10), nullable=False),
        sa.Column("prod_date", sa.Date(), nullable=True),
        sa.Column("oil", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column("gas", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column("water", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column(
            "gas_normalized_to_10k_ft", sa.Numeric(precision=19, scale=2), nullable=True
        ),
        sa.Column(
            "oil_normalized_to_10k_ft", sa.Numeric(precision=19, scale=2), nullable=True
        ),
        sa.Column(
            "gas_normalized_to_7500_ft",
            sa.Numeric(precision=19, scale=2),
            nullable=True,
        ),
        sa.Column(
            "oil_normalized_to_7500_ft",
            sa.Numeric(precision=19, scale=2),
            nullable=True,
        ),
        sa.Column(
            "gas_normalized_to_5k_ft", sa.Numeric(precision=19, scale=2), nullable=True
        ),
        sa.Column(
            "oil_normalized_to_5k_ft", sa.Numeric(precision=19, scale=2), nullable=True
        ),
        sa.Column("prod_day", sa.Numeric(precision=19, scale=2), nullable=True),
        sa.Column("prod_month", sa.Integer(), nullable=True),
        sa.Column("peak_norm_month", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("api10"),
    )
    op.create_index(
        op.f("ix_production_monthly_api10"),
        "production_monthly",
        ["api10"],
        unique=False,
    )
    op.create_table(
        "well",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api14", sa.String(length=14), nullable=False),
        sa.Column("api10", sa.String(length=10), nullable=True),
        sa.Column("hole_direction", sa.String(length=1), nullable=True),
        sa.Column("is_producing", sa.Integer(), nullable=True),
        sa.Column("operator", sa.String(), nullable=True),
        sa.Column("hist_operator", sa.String(), nullable=True),
        sa.Column("primary_product", sa.String(length=10), nullable=True),
        sa.Column("perfll", sa.Integer(), nullable=True),
        sa.Column("lateral_length", sa.Integer(), nullable=True),
        sa.Column("frac_bbl", sa.Integer(), nullable=True),
        sa.Column("frac_lb", sa.Integer(), nullable=True),
        sa.Column("frac_bbl_ft", sa.Integer(), nullable=True),
        sa.Column("frac_lb_ft", sa.Integer(), nullable=True),
        sa.Column("frac_gen_int", sa.Integer(), nullable=True),
        sa.Column("frac_gen_str", sa.String(), nullable=True),
        sa.Column("comp_date", sa.Date(), nullable=True),
        sa.Column("spud_date", sa.Date(), nullable=True),
        sa.Column("permit_date", sa.Date(), nullable=True),
        sa.Column("abandoned_date", sa.Date(), nullable=True),
        sa.Column("rig_release_date", sa.Date(), nullable=True),
        sa.Column("last_activity_date", sa.Date(), nullable=True),
        sa.Column("basin", sa.String(length=50), nullable=True),
        sa.Column("state", sa.String(length=50), nullable=True),
        sa.Column("county", sa.String(length=50), nullable=True),
        sa.Column("shllon", sa.Float(), nullable=True),
        sa.Column("shllat", sa.Float(), nullable=True),
        sa.Column("bhllon", sa.Float(), nullable=True),
        sa.Column("bhllat", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("api14"),
    )
    op.create_index(op.f("ix_well_api10"), "well", ["api10"], unique=False)
    op.create_index(op.f("ix_well_api14"), "well", ["api14"], unique=False)
    op.create_index(
        op.f("ix_well_hist_operator"), "well", ["hist_operator"], unique=False
    )
    op.create_index(op.f("ix_well_operator"), "well", ["operator"], unique=False)
    op.create_table(
        "well_links",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api14", sa.String(length=14), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("value", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("api14", "name"),
    )
    op.create_index(op.f("ix_well_links_api14"), "well_links", ["api14"], unique=False)
    op.create_index(op.f("ix_well_links_name"), "well_links", ["name"], unique=False)
    op.create_table(
        "wellstats",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("api14", sa.String(length=14), nullable=False),
        sa.Column("wellbore_crow_length", sa.Integer(), nullable=True),
        sa.Column("wellbore_direction", sa.String(length=1), nullable=True),
        sa.Column("wellbore_bearing", sa.Float(), nullable=True),
        sa.Column("wellbore_dls_roc", sa.Float(), nullable=True),
        sa.Column("lateral_dls_roc", sa.Float(), nullable=True),
        sa.Column("wellbore_dls_mc", sa.Float(), nullable=True),
        sa.Column("lateral_dls_mc", sa.Float(), nullable=True),
        sa.Column("nearest_deo_prospect", sa.String(length=50), nullable=True),
        sa.Column("dist_to_deo_prospect_mi", sa.Float(), nullable=True),
        sa.Column("nearest_deo_api10", sa.String(length=50), nullable=True),
        sa.Column("dist_to_deo_well_mi", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("api14"),
    )
    op.create_index(op.f("ix_wellstats_api14"), "wellstats", ["api14"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_wellstats_api14"), table_name="wellstats")
    op.drop_table("wellstats")
    op.drop_index(op.f("ix_well_links_name"), table_name="well_links")
    op.drop_index(op.f("ix_well_links_api14"), table_name="well_links")
    op.drop_table("well_links")
    op.drop_index(op.f("ix_well_operator"), table_name="well")
    op.drop_index(op.f("ix_well_hist_operator"), table_name="well")
    op.drop_index(op.f("ix_well_api14"), table_name="well")
    op.drop_index(op.f("ix_well_api10"), table_name="well")
    op.drop_table("well")
    op.drop_index(op.f("ix_production_monthly_api10"), table_name="production_monthly")
    op.drop_table("production_monthly")
    op.drop_index(op.f("ix_prodstats_api10"), table_name="prodstats")
    op.drop_table("prodstats")
    op.drop_index(op.f("ix_depths_name"), table_name="depths")
    op.drop_index(op.f("ix_depths_api14"), table_name="depths")
    op.drop_table("depths")
    # ### end Alembic commands ###
