"""empty message

Revision ID: 868c806bffeb
Revises: 080ec40e892b
Create Date: 2020-04-14 10:35:24.539224

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "868c806bffeb"
down_revision = "080ec40e892b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("areas", "entity_type")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas",
        sa.Column(
            "entity_type", sa.VARCHAR(length=255), autoincrement=False, nullable=False
        ),
    )
    # ### end Alembic commands ###
