"""empty message

Revision ID: 9478628c4f68
Revises: a3104b309bab
Create Date: 2020-03-16 12:56:45.688302

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9478628c4f68"
down_revision = "a3104b309bab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_header",
        sa.Column("boe_pdp_last3mo_per30Kbbl", sa.Integer(), nullable=True),
    )
    op.add_column(
        "production_header",
        sa.Column("oil_pdp_last3mo_per30Kbbl", sa.Integer(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("production_header", "oil_pdp_last3mo_per30Kbbl")
    op.drop_column("production_header", "boe_pdp_last3mo_per30Kbbl")
    # ### end Alembic commands ###
