"""empty message

Revision ID: 9d248e7c87b4
Revises: 868c806bffeb
Create Date: 2020-04-16 11:26:08.700867

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "9d248e7c87b4"
down_revision = "868c806bffeb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas", sa.Column("h_last_run_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "areas",
        sa.Column(
            "id", sa.Integer(), autoincrement=True, nullable=False, primary_key=True
        ),
    )
    op.add_column(
        "areas",
        sa.Column(
            "providers",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default="[]",
            nullable=False,
        ),
    )
    op.add_column(
        "areas", sa.Column("v_last_run_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.alter_column("areas", "area", existing_type=sa.VARCHAR(length=25), nullable=True)
    op.create_unique_constraint(op.f("uq_areas_area"), "areas", ["area"])
    op.drop_column("areas", "last_run_at")
    op.drop_column("areas", "hole_direction")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "areas",
        sa.Column(
            "hole_direction",
            sa.VARCHAR(length=255),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.add_column(
        "areas",
        sa.Column(
            "last_run_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_constraint(op.f("uq_areas_area"), "areas", type_="unique")
    op.alter_column(
        "areas", "area", existing_type=sa.VARCHAR(length=25), nullable=False
    )
    op.drop_column("areas", "v_last_run_at")
    op.drop_column("areas", "providers")
    op.drop_column("areas", "id")
    op.drop_column("areas", "h_last_run_at")
    # ### end Alembic commands ###
