"""empty message

Revision ID: 9e03472c1f6c
Revises: 3f8b8e9987d4
Create Date: 2020-04-18 15:56:01.074664

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9e03472c1f6c"
down_revision = "3f8b8e9987d4"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        "ix_lateral_partial",
        "survey_points",
        ["api14", "is_in_lateral"],
        unique=False,
        postgresql_where=sa.text("is_in_lateral"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_lateral_partial", table_name="survey_points")
    # ### end Alembic commands ###
