"""empty message

Revision ID: 9fe0cd284f0b
Revises: 4b9cf99f1075
Create Date: 2020-04-03 21:23:48.043769

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "9fe0cd284f0b"
down_revision = "4b9cf99f1075"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "depths", sa.Column("aggregate_type", sa.String(length=25), nullable=True)
    )
    op.add_column(
        "depths", sa.Column("property_name", sa.String(length=50), nullable=True)
    )
    op.create_index(
        "prodstat_api10_prop_agg_idx",
        "prodstats",
        ["api10", "property_name", "aggregate_type"],
        unique=False,
    )
    op.add_column("wells", sa.Column("md", sa.Integer(), nullable=True))
    op.add_column("wells", sa.Column("tvd", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wells", "tvd")
    op.drop_column("wells", "md")
    op.drop_index("prodstat_api10_prop_agg_idx", table_name="prodstats")
    op.drop_column("depths", "property_name")
    op.drop_column("depths", "aggregate_type")
    # ### end Alembic commands ###
