"""empty message

Revision ID: a3104b309bab
Revises: 0dd4334dbd5d
Create Date: 2020-03-13 13:57:10.228257

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a3104b309bab"
down_revision = "0dd4334dbd5d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "production_monthly", sa.Column("boe_norm_3k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("gas_norm_3k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("oil_norm_3k", sa.Integer(), nullable=True)
    )
    op.add_column(
        "production_monthly", sa.Column("water_norm_3k", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("production_monthly", "water_norm_3k")
    op.drop_column("production_monthly", "oil_norm_3k")
    op.drop_column("production_monthly", "gas_norm_3k")
    op.drop_column("production_monthly", "boe_norm_3k")
    # ### end Alembic commands ###
