"""empty message

Revision ID: cc2f89e459b0
Revises: 9fe0cd284f0b
Create Date: 2020-04-11 13:18:33.057458

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "cc2f89e459b0"
down_revision = "9fe0cd284f0b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("depths", sa.Column("assignment_method", sa.String(), nullable=True))
    op.create_index(
        op.f("ix_production_header_primary_api14"),
        "production_header",
        ["primary_api14"],
        unique=False,
    )
    op.add_column(
        "wells", sa.Column("provider_status", sa.String(length=50), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("wells", "provider_status")
    op.drop_index(
        op.f("ix_production_header_primary_api14"), table_name="production_header"
    )
    op.drop_column("depths", "assignment_method")
    # ### end Alembic commands ###
