"""empty message

Revision ID: d7da4e4d0cc1
Revises: 7bff459916df
Create Date: 2020-04-11 15:15:52.318397

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d7da4e4d0cc1"
down_revision = "7bff459916df"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "frac_parameters",
        sa.Column("lateral_length_type", sa.String(length=25), nullable=True),
    )
    op.add_column(
        "frac_parameters", sa.Column("lateral_lenth", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("frac_parameters", "lateral_lenth")
    op.drop_column("frac_parameters", "lateral_length_type")
    # ### end Alembic commands ###
