"""empty message

Revision ID: d93f5866d24b
Revises: 2bc48932d125
Create Date: 2020-04-18 15:10:20.942726

"""
import geoalchemy2
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d93f5866d24b"
down_revision = "2bc48932d125"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("survey_points", "geom_webmercator")
    op.drop_column("surveys", "wellbore_webmercator")
    op.drop_column("surveys", "stick_webmercator")
    op.drop_column("surveys", "bent_stick_webmercator")
    op.drop_column("surveys", "lateral_only_webmercator")
    op.drop_column("well_locations", "geom_webmercator")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "well_locations",
        sa.Column(
            "geom_webmercator",
            geoalchemy2.types.Geometry(geometry_type="POINT", srid=3857),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "surveys",
        sa.Column(
            "lateral_only_webmercator",
            geoalchemy2.types.Geometry(geometry_type="LINESTRING", srid=3857),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "surveys",
        sa.Column(
            "bent_stick_webmercator",
            geoalchemy2.types.Geometry(geometry_type="LINESTRING", srid=3857),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "surveys",
        sa.Column(
            "stick_webmercator",
            geoalchemy2.types.Geometry(geometry_type="LINESTRING", srid=3857),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "surveys",
        sa.Column(
            "wellbore_webmercator",
            geoalchemy2.types.Geometry(geometry_type="LINESTRING", srid=3857),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "survey_points",
        sa.Column(
            "geom_webmercator",
            geoalchemy2.types.Geometry(geometry_type="POINT", srid=3857),
            autoincrement=False,
            nullable=True,
        ),
    )
    # ### end Alembic commands ###
